FROM node:16.10.0-alpine3.14 AS vue-build

RUN apk update && apk upgrade

COPY ./app-vue/ /forsyningsdata/

RUN npm install -g @vue/cli
WORKDIR /forsyningsdata
RUN npm install --legacy-peer-deps
RUN npm run build-prod




FROM nginx:1.21.3-alpine

RUN apk update && apk upgrade

RUN apk add openssl libaio

RUN adduser nginx root

RUN mkdir -p /data/nginx/ramcache/assets && mkdir -p /data/nginx/ramcache/elasticsearch
RUN mkdir -p /data/nginx/assets

COPY --from=vue-build /forsyningsdata/dist /usr/share/nginx/html
COPY ./nginx.prod.conf /etc/nginx/nginx.conf

RUN apk add tzdata
RUN export TZ="Europe/Copenhagen"
RUN cp /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime
RUN echo "Europe/Copenhagen" > /etc/timezone
RUN apk del tzdata

EXPOSE 80
EXPOSE 443
