FROM node:16.13.1-alpine3.14 AS vue-build

RUN apk update && apk upgrade

COPY ./app-vue/ /transform/

RUN npm install -g @vue/cli
WORKDIR /transform
RUN npm install --legacy-peer-deps
RUN npm run build-test




FROM nginx:1.21.4-alpine

RUN apk update && apk upgrade

RUN apk add openssl libaio

RUN adduser nginx root

RUN mkdir -p /data/nginx/ramcache/assets && mkdir -p /data/nginx/ramcache/elasticsearch
RUN mkdir -p /data/nginx/assets

COPY --from=vue-build /transform/dist /usr/share/nginx/html
COPY ./nginx.test.conf /etc/nginx/nginx.conf

RUN apk add tzdata
RUN export TZ="Europe/Copenhagen"
RUN cp /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime
RUN echo "Europe/Copenhagen" > /etc/timezone
RUN apk del tzdata
