version: '3.8'

services:

  forsyningsdata:
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        # for Traefik V2
        - "traefik.http.routers.forsyningsdata-redirect.entrypoints=web"
        - "traefik.http.routers.forsyningsdata-redirect.rule=Host(`forsyningsdataportal.dk`, `forsyningsdata.dk`, `forsyningsdata.dataforsyningen.dk`)"
        - "traefik.http.routers.forsyningsdata-redirect.middlewares=secHeadersAndRedirect@file"
        - "traefik.http.routers.forsyningsdata.entrypoints=websecure"
        - "traefik.http.routers.forsyningsdata.rule=Host(`forsyningsdataportal.dk`, `forsyningsdata.dk`, `forsyningsdata.dataforsyningen.dk`)"
        - "traefik.http.routers.forsyningsdata.tls.certresolver=letsencrypt"
        - "traefik.http.routers.forsyningsdata.tls.domains[0].main=forsyningsdataportal.dk"
        - "traefik.http.routers.forsyningsdata.tls.domains[1].main=forsyningsdata.dk"
        - "traefik.http.routers.forsyningsdata.tls.domains[2].main=forsyningsdata.dataforsyningen.dk"
        - "traefik.http.services.forsyningsdata.loadbalancer.server.port=80"
    image: kortforsyningen/forsyningsdata:prod-latest
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - type: volume
        source: pim_assets
        target: /data/nginx/assets
        consistency: cached
        read_only: true
        volume:
          nocopy: true
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true

volumes:
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  pim_assets:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=loadfs8.kmsext.dk,rw,async,vers=4,rsize=65536,hard,tcp,timeo=600,intr,bg,ac,sec=sys,lookupcache=pos,nolock"
      device: ":/data/kmsloadfs3/data/PIM/pimcore/web/var/assets"
