FROM node:16.13.0-alpine3.14 AS vue-build

RUN apk update && apk upgrade

COPY ./hkpn-vue/ /hkpn/

RUN npm install -g @vue/cli \
  @vue/cli-service \
  @vue/cli-plugin-babel \
  @vue/cli-plugin-eslint \
  @vue/cli-plugin-pwa \
  @vue/cli-plugin-router \
  @vue/cli-plugin-vuex \
  @vue/compiler-sfc \
  vue-cli-plugin-style-resources-loader
WORKDIR /hkpn
#RUN npm install && npm audit fix
RUN npm install --legacy-peer-deps
RUN npm run build-prod




FROM nginx:1.21.3-alpine

RUN apk update && apk upgrade

RUN apk add openssl libaio

RUN adduser nginx root

RUN mkdir -p /data/nginx/ramcache/assets && mkdir -p /data/nginx/ramcache/elasticsearch
RUN mkdir -p /data/nginx/assets

COPY --from=vue-build /hkpn/dist /usr/share/nginx/html
COPY ./nginx.prod.conf /etc/nginx/nginx.conf
COPY ./SecHeaders.conf /etc/nginx/SecHeaders.conf

RUN apk add tzdata
RUN export TZ="Europe/Copenhagen"
RUN cp /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime
RUN echo "Europe/Copenhagen" > /etc/timezone
RUN apk del tzdata

EXPOSE 80
EXPOSE 443
